### ISSUE TITLE
アプリを追加しても反映されない

### ISSUE THREAD

**Issue by popkechupki** [CoSSeDevelopmentTeam/CoSSePhoneCore#2]
コアのデーターベースが既に作成され、最初にアプリを導入した以降にデフォルトでインストールされる設定のアプリを入れて起動してもメニューに表示されない。また、既存のアプリを選択するとその表示されないアプリの画面が出てきたりする。

**Comment by itsu020402** [comment]
https://github.com/CoSSeDevelopmentTeam/CoSSePhoneCore/commit/eeccb91c5070d2018f18fb8f12bf2f1f6370b26b
